sudo: required
services:
  - docker

before_install:
  - docker build -t dzianismatveyenka/docker-react -f Dockerfile.dev .

script:
  - docker run dzianismatveyenka/docker-react npm run test -- --coverage